thefarm exercise interfaces
exercism/go pull request #1976
Opened 2021-12-02 19:32 UTC by jmrunkle

2021-12-03 12:32 UTC, kahgoh requested changes
Just adding some suggestions to fix or improve some wording.

2021-12-03 12:32 UTC, kahgoh commented on exercises/concept/the-farm/.docs/introduction.md
> +When no errors have to be returned, return `nil` for the error:
```suggestion
Return `nil` for the error when there are no errors:
```

2021-12-03 12:32 UTC, kahgoh commented on exercises/concept/the-farm/.docs/introduction.md
> +In Go, it is also a best practice to avoid declaring variables in a scope if these are not required later.
```suggestion
In Go, it is also a best practice to avoid declaring variables in a scope if they are not required later.
```

2021-12-12 12:35 UTC, junedev approved these changes

2021-12-12 12:36 UTC, junedev commented
For some reason I can't push my fixes to the branch here. I will merge this as is and create an additional PR for the updates.

2021-12-12 12:37 UTC, merged