New concept First-Class Functions
exercism/go pull request #2103
Opened 2022-02-17 22:47 UTC by antklim

Hi exercism team.

I'm not sure whether this concept is already planned or being worked on. And I apologise if I'm creating inconveniences. 

I was learning different languages by reading books and using your platform. I found that the first-class functions are a powerful tool that is used by developers every day, but sometimes we don't even realise it. I would like to share my knowledge and expertise on this subject. That is a reason to create this PR.

I'm sorry for opening such a big pull request. I wasn't sure what will be the best way to create a new concept and support it with the practice exercise. Please let me know if you would like it to be split into smaller PRs. 

Thanks,
Anton

2022-02-27 19:38 UTC, andrerfcsantos requested changes
Thanks for this!

Since this is indeed a big PR, took us a while to get back to you, sorry for that.

First class functions is something that we had planned on our [Roadmap](https://exercism.org/docs/tracks/go/roadmap#h-potential-future-concepts) as a potential future concept and not something that was meant to me implemented soon. Concepts that we mean to implement all have their own issues that are being tracked [here](https://github.com/exercism/go/issues/1886). The advantage of having an issue associated to each concept exercise is that we can discuss some things on the issue itself and agree on a general implementation before actually implementing it.

Despite this PR not following the expected flow for a concept exercise, I think we can accommodate this in our current concept tree!

Overall the PR is really good. It shows that you took your time with it, so thank you for that!

I did some initial review requesting changes, let me know what you think of them.

2022-02-27 19:38 UTC, andrerfcsantos commented on exercises/concept/expenses/.meta/exemplar.go
> +func byDatePeriod(p DatePeriod) func(Record) bool {
I really like the idea of `byDatePeriod` and `byCategory` as good exercises to practice returning functions.

However, I think they should be on their own task. In another comment, I suggested the making of `Filter` also be a task and be the first one, and I think these functions could be the tasks next to that one.

That way, we have these tasks acting as "checkpoints" before the task where we ask the student to write `Total`.

2022-02-27 19:38 UTC, andrerfcsantos commented on exercises/concept/expenses/.docs/instructions.md
> +## 2. Find the top N expenses categories in period
I think this task should be removed. Adds considerable amount of busy work like sorting, that doesn't necessarily help the student learn more about functions as first-class values.

See the other comments for suggestions on additional tasks. I believe with those additional tasks, this one becomes unnecessary.

2022-03-01 18:56 UTC, antklim commented on concepts/first-class-functions/about.md
> +It is possible thanks to the function types in Go. A function type denotes the set of all functions with the same sequence of parameter types and the same sequence of result types. User-defined types
Ok, got it. I will update examples. Thanks for the help.

2022-03-01 18:59 UTC, antklim commented on exercises/concept/expenses/expenses.go
> +func (rr Records) Filter(f func(Record) bool) Records {
Not a problem, I will update the exercise accordingly.

2022-03-01 19:01 UTC, antklim commented on exercises/concept/expenses/.docs/instructions.md
> +oct2000 := DatePeriod{From: "2000-10-01", To: "2000-10-31"}
Sure, I'll alter the examples to show the creation of `time.Time`.

2022-03-27 15:17 UTC, andrerfcsantos requested changes
This is looking ever better!

The main suggestion here is to replace the use of real times to a simpler version of time that can be represented by just a number (i.e, number of days). I also suggested other minor fixes. After these changes, I think we can launch the exercise.

2022-03-27 15:17 UTC, andrerfcsantos commented on exercises/concept/expenses/expenses.go
> +func Filter(in []Record, f func(Record) bool) (out []Record) {
```suggestion
func Filter(in []Record, f func(Record) bool) []Record {
```

As much as possible, we try to discourage the use of named returns.

2022-03-27 15:17 UTC, andrerfcsantos commented on exercises/concept/expenses/expenses.go
> +	panic("Filter not implemented")
```suggestion
	panic("Please implement the Filter function.")
```

Just to make the message look consistent with others from other exercises.

2022-03-27 15:17 UTC, andrerfcsantos commented on exercises/concept/expenses/expenses.go
> +	panic("ByDatePeriod not implemented")
```suggestion
	panic("Please implement the ByDatePeriod function.")
```

Just to make the message look consistent with others from other exercises.

2022-03-27 15:17 UTC, andrerfcsantos commented on exercises/concept/expenses/expenses.go
> +	panic("ByCategory not implemented")
```suggestion
	panic("Please implement the ByCategory function.")
```

Just to make the message look consistent with others from other exercises.

2022-03-27 15:17 UTC, andrerfcsantos commented on exercises/concept/expenses/expenses.go
> +	panic("Total not implemented")
```suggestion
	panic("Please implement the Total function.")
```

Just to make the message look consistent with others from other exercises.

2022-03-27 15:17 UTC, andrerfcsantos commented on exercises/concept/expenses/expenses.go
> +	panic("CategoryExpenses not implemented")
```suggestion
	panic("Please implement the CategoryExpenses function.")
```

Just to make the message look consistent with others from other exercises.

2022-03-27 15:17 UTC, andrerfcsantos commented on concepts/first-class-functions/about.md
> +Another powerful tool that is available thanks to first-class functions support is anonymous functions. Anonymous functions are defined at treir point of use, without a name following the `func` keyw
```suggestion
Another powerful tool that is available thanks to first-class functions support is anonymous functions. Anonymous functions are defined at their point of use, without a name following the `func` keyword. Such functions have access to the variables of the enclosing function. For example:
```

2022-03-27 15:17 UTC, andrerfcsantos commented on exercises/concept/expenses/.meta/design.md
> +
```suggestion
## Concepts

- `first-class-functions`

```

2022-03-29 23:19 UTC, antklim commented
Hi @andrerfcsantos, thanks a lot for the reviews! I hope I addressed all the comments now. Please let me know if there are more improvements that need to be done. 
Also, I have a question. What status should the `expenses` exercise have? I put it to `wip` in `config.json`. Should it be changed to `beta` or any other status?
Thanks

2022-04-02 22:58 UTC, andrerfcsantos approved these changes
Since this PR is going for a while and to not take much of your time and effort, I just did some final touches to the exercise. The main thing was to update the hints to match the changes made to the exercise and add some clarifications in the text.

Thank you for all the work and patience in getting this exercise ready!

2022-04-02 22:58 UTC, merged