minesweeper-api-change
exercism/go pull request #2118
Opened 2022-03-02 21:17 UTC by norbs57

Minesweeper exercise, issue [#2046](https://github.com/exercism/go/issues/2046)

- Changed API to `func Annotate(board []string) []string` 
- Replaced tests with canonical tests
- Defined `testAnnotate` using `T.run`
- Replaced sample solution with two new examples 
- Updated `config.json`

2022-03-03 12:13 UTC, andrerfcsantos requested changes
Thanks for working on this!

Left some suggestions.

2022-03-03 22:11 UTC, norbs57 commented on exercises/practice/minesweeper/minesweeper_test.go
> +}
Will do. It seems a bit of a chore to keep checking this, so I wonder if there is an automatic way to add a newline at the end if absent?

2022-03-04 00:01 UTC, andrerfcsantos requested changes
I like the shape this is taking!

Some final suggestions that escaped my initial review.

2022-03-04 00:02 UTC, andrerfcsantos commented on exercises/practice/minesweeper/minesweeper_test.go
> +}
I agree we should see a good way to automate tasks like this. Right now, there isn't.

2022-03-05 15:37 UTC, andrerfcsantos approved these changes
Thanks for this!

Merged 🚀

2022-03-05 15:38 UTC, merged