Improve exercise nth-prime
exercism/go pull request #2225
Opened 2022-05-27 14:28 UTC by MikaeelMF

Hi!
According to issue #2224, I have changed this exercise to require an error instead of a boolean in case of input out of range.

2022-05-27 14:38 UTC, MikaeelMF commented
I don't understand why the linter things `err` is a boolean.

2022-05-27 15:04 UTC, andrerfcsantos commented
@MikaeelMF For changes like this, you must also change the [exemple.go](https://github.com/exercism/go/blob/main/exercises/practice/nth-prime/.meta/example.go) of the solution. It's this solution that is being used for the tests. If you are curious, [this is the script](https://github.com/exercism/go/blob/main/bin/test-without-stubs) that is being ran to perform the tests. Note that it looks for an `.meta/example.go` or an `.meta/exemplar.go` and copies it to a temporary dir and then runs the tests on that dir. This is most likely the reason the tests are failing.

Keeping your branches up-to-date with this repo is a good idea. However, you don't necessarily need a new PR if your version is outdated. You can rebase the branch of this pr (your `main` branch) with the main branch of the remote you have configured for the `exercism/go` remote. You most likely won't have conflicts, and if you do, I don't think they'll be big/hard to solve. Then force pushing your main after that rebase will update the PR.

And don't worry about the commit history. Even if you do several commits for the PR, when merging, we always squash them into a single one automatically, so the history always looks clean. So make as many commits as you want. Your branch, your rules :)

2022-05-28 19:10 UTC, andrerfcsantos requested changes
Some more suggestions, after that we can merge :)

2022-05-28 19:10 UTC, andrerfcsantos commented on exercises/practice/nth-prime/cases_test.go
> +		errors.New("Input must be greater than 1"),
```suggestion
		errors.New("input must be greater than 1"),
```

In Go, error messages are usually not capitalized.

2022-05-28 21:47 UTC, MikaeelMF commented
@andrerfcsantos 
All done! Thank you for the suggestions!

2022-05-29 11:41 UTC, andrerfcsantos approved these changes

2022-05-29 11:56 UTC, andrerfcsantos commented
@MikaeelMF Looks great! Made just a little change to add you to the list of contributors to the exercise - the changes you made were are significant enough to justify it :)

2022-05-29 12:00 UTC, merged

2022-05-29 13:35 UTC, MikaeelMF commented
> @MikaeelMF Looks great! Made just a little change to add you to the list of contributors to the exercise - the changes you made were are significant enough to justify it :)

Wow, Awesome! Thanks!