improved output for simple_cipher test
exercism/go pull request #2288
Opened 2022-07-07 12:25 UTC by iAutomator

### Fixes
- made tests to output all failed data examples instead of one only

_Before_
```
=== RUN   TestShift
    simple_cipher_test.go:58: Shift(3) Encode("Go, go, gophers") = "jrWjrWjrskhuv", want "jrjrjrskhuv".
```
_Now_
```
=== RUN   TestShift
    simple_cipher_test.go:58: Shift(3) Encode("Go, go, gophers") = "jrWjrWjrskhuv", want "jrjrjrskhuv".
    simple_cipher_test.go:58: Shift(3) Encode("I am a panda bear.") = "lWdpWdWsdqgdWehdu", want "ldpdsdqgdehdu".
    simple_cipher_test.go:58: Shift(3) Encode("Programming is AWESOME!") = "surjudpplqjWlvWdzhvrph", want "surjudpplqjlvdzhvrph". 
```
- changed Encode test error log to contain an original string instead of the one with cleared extra symbols

_Before_
```
simple_cipher_test.go:26: Caesar Encode("todayisholiday") = "wrgdlvkrolgd", want "wrgdblvkrolgdb".
```
_Now_
```
simple_cipher_test.go:58: Caesar Encode("today is holiday") = "wrgdlvkrolgd", want "wrgdblvkrolgdb".
```

2022-07-07 13:49 UTC, andrerfcsantos requested changes
I agree that we should show the output for the other failed tests, but let me suggest another way to do this.

Right now we are not using subtests for this exercise, and subtests can have calls to `t.Fatalf` in them, but still allow the other tests to run. We are in the process of converting the tests on the track to subtests, you can read more about this here: https://github.com/exercism/go/issues/2098

So my suggestion would be to convert the tests for this exercise into subtests, and keep the calls to `t.Fatalf` inside the subtests. This way we fix 2 issues at once :)

When doing subtests, the call to `t.Run` expects a "test name" as the first argument. Right now it seems we don't have descriptions attached to each test case. My suggestion would be to add a description field to the `prepped` and `cipherTest` structs and grab the descriptions for the tests from [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/state-of-tic-tac-toe/canonical-data.json). If there's a test that we have that is not present in that json file, feel free to write a small description for the test. If there are tests in the json file that we don't currently have, ignore those and we'll add them at a later date.

Let me know if you would you like to implement subtests for the tests of this exercise. I know this is a bigger ask than what you probably intended originally, so I totally get if you don't want to do this. But I truly believe this is the right way to fix this issue. If you make these changes, I'll make sure to size the PR accordingly so you get a little bit more rep for the extra work.

2022-07-08 08:31 UTC, iAutomator commented
applied subtests so now output is as follows
```
PS C:\Users\iavto\Documents\exercism_tasks\go\simple-cipher> go test -v -run TestCaesar
=== RUN   TestCaesar
=== RUN   TestCaesar/no_extra_symbols
=== RUN   TestCaesar/no_extra_symbols/Encode(iamapandabear)
=== RUN   TestCaesar/no_extra_symbols/Decode(ldpdsdqgdehdu)
=== RUN   TestCaesar/no_extra_symbols/Encode(programmingisawesome)
=== RUN   TestCaesar/no_extra_symbols/Decode(surjudpplqjlvdzhvrph)
=== RUN   TestCaesar/no_extra_symbols/Encode(todayisholiday)
=== RUN   TestCaesar/no_extra_symbols/Decode(wrgdblvkrolgdb)
=== RUN   TestCaesar/no_extra_symbols/Encode(venividivici)
=== RUN   TestCaesar/no_extra_symbols/Decode(yhqlylglylfl)
=== RUN   TestCaesar/with_extra_symbols
=== RUN   TestCaesar/with_extra_symbols/Encode(Go,_go,_gophers)
    simple_cipher_test.go:46: Encode(Go, go, gophers): got "qqqqq", want "jrjrjrskhuv".
=== RUN   TestCaesar/with_extra_symbols/Decode(jrjrjrskhuv)
=== RUN   TestCaesar/with_extra_symbols/Encode(I_am_a_panda_bear.)
=== RUN   TestCaesar/with_extra_symbols/Decode(ldpdsdqgdehdu)
=== RUN   TestCaesar/with_extra_symbols/Encode(Programming_is_AWESOME!)
=== RUN   TestCaesar/with_extra_symbols/Decode(surjudpplqjlvdzhvrph)
=== RUN   TestCaesar/with_extra_symbols/Encode(today_is_holiday)
=== RUN   TestCaesar/with_extra_symbols/Decode(wrgdblvkrolgdb)
=== RUN   TestCaesar/with_extra_symbols/Encode(Twas_the_night_before_Christmas)
=== RUN   TestCaesar/with_extra_symbols/Decode(wzdvwkhqljkwehiruhfkulvwpdv)
=== RUN   TestCaesar/with_extra_symbols/Encode(_--_@#!)
=== RUN   TestCaesar/with_extra_symbols/Decode()
=== RUN   TestCaesar/with_extra_symbols/Encode()
=== RUN   TestCaesar/with_extra_symbols/Decode()#01
--- FAIL: TestCaesar (0.01s)
    --- PASS: TestCaesar/no_extra_symbols (0.00s)
        --- PASS: TestCaesar/no_extra_symbols/Encode(iamapandabear) (0.00s)
        --- PASS: TestCaesar/no_extra_symbols/Decode(ldpdsdqgdehdu) (0.00s)
        --- PASS: TestCaesar/no_extra_symbols/Encode(programmingisawesome) (0.00s)
        --- PASS: TestCaesar/no_extra_symbols/Decode(surjudpplqjlvdzhvrph) (0.00s)
        --- PASS: TestCaesar/no_extra_symbols/Encode(todayisholiday) (0.00s)
        --- PASS: TestCaesar/no_extra_symbols/Decode(wrgdblvkrolgdb) (0.00s)
        --- PASS: TestCaesar/no_extra_symbols/Encode(venividivici) (0.00s)
        --- PASS: TestCaesar/no_extra_symbols/Decode(yhqlylglylfl) (0.00s)
    --- FAIL: TestCaesar/with_extra_symbols (0.00s)
        --- FAIL: TestCaesar/with_extra_symbols/Encode(Go,_go,_gophers) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Decode(jrjrjrskhuv) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Encode(I_am_a_panda_bear.) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Decode(ldpdsdqgdehdu) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Encode(Programming_is_AWESOME!) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Decode(surjudpplqjlvdzhvrph) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Encode(today_is_holiday) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Decode(wrgdblvkrolgdb) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Encode(Twas_the_night_before_Christmas) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Decode(wzdvwkhqljkwehiruhfkulvwpdv) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Encode(_--_@#!) (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Decode() (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Encode() (0.00s)
        --- PASS: TestCaesar/with_extra_symbols/Decode()#01 (0.00s)
```

```
PS C:\Users\iavto\Documents\exercism_tasks\go\simple-cipher> go test -v -run TestShift 
=== RUN   TestShift
=== RUN   TestShift/key=3
=== RUN   TestShift/key=3/Encode(Go,_go,_gophers)
    simple_cipher_test.go:46: Encode(Go, go, gophers): got "qqqqq", want "jrjrjrskhuv".
=== RUN   TestShift/key=3/Decode(jrjrjrskhuv)
=== RUN   TestShift/key=3/Encode(I_am_a_panda_bear.)
=== RUN   TestShift/key=3/Decode(ldpdsdqgdehdu)
=== RUN   TestShift/key=3/Encode(Programming_is_AWESOME!)
=== RUN   TestShift/key=3/Decode(surjudpplqjlvdzhvrph)
=== RUN   TestShift/key=3/Encode(today_is_holiday)
=== RUN   TestShift/key=3/Decode(wrgdblvkrolgdb)
=== RUN   TestShift/key=3/Encode(Twas_the_night_before_Christmas)
=== RUN   TestShift/key=3/Decode(wzdvwkhqljkwehiruhfkulvwpdv)
=== RUN   TestShift/key=3/Encode(_--_@#!)
=== RUN   TestShift/key=3/Decode()
=== RUN   TestShift/key=3/Encode()
=== RUN   TestShift/key=3/Decode()#01
=== RUN   TestShift/key=-3
=== RUN   TestShift/key=-3/Encode(THE_ENEMY_IS_NEAR)
=== RUN   TestShift/key=-3/Decode(qebbkbjvfpkbxo)
=== RUN   TestShift/key=-3/Encode(SPIES_SEND_SECRET_MESSAGES)
=== RUN   TestShift/key=-3/Decode(pmfbppbkapbzobqjbppxdbp)
=== RUN   TestShift/key=-3/Encode(THOMAS_JEFFERSON_DESIGNED_A_SUBSTITUTION_CIPHER)
=== RUN   TestShift/key=-3/Decode(qeljxpgbccboplkabpfdkbaxprypqfqrqflkzfmebo)
=== RUN   TestShift/key=-3/Encode(the_quick_brown_fox_jumps_over_the_lazy_dog)
=== RUN   TestShift/key=-3/Decode(qebnrfzhyoltkclugrjmplsboqebixwvald)
--- FAIL: TestShift (0.01s)
    --- FAIL: TestShift/key=3 (0.00s)
        --- FAIL: TestShift/key=3/Encode(Go,_go,_gophers) (0.00s)
        --- PASS: TestShift/key=3/Decode(jrjrjrskhuv) (0.00s)
        --- PASS: TestShift/key=3/Encode(I_am_a_panda_bear.) (0.00s)
        --- PASS: TestShift/key=3/Decode(ldpdsdqgdehdu) (0.00s)
        --- PASS: TestShift/key=3/Encode(Programming_is_AWESOME!) (0.00s)
        --- PASS: TestShift/key=3/Decode(surjudpplqjlvdzhvrph) (0.00s)
        --- PASS: TestShift/key=3/Encode(today_is_holiday) (0.00s)
        --- PASS: TestShift/key=3/Decode(wrgdblvkrolgdb) (0.00s)
        --- PASS: TestShift/key=3/Encode(Twas_the_night_before_Christmas) (0.00s)
        --- PASS: TestShift/key=3/Decode(wzdvwkhqljkwehiruhfkulvwpdv) (0.00s)
        --- PASS: TestShift/key=3/Encode(_--_@#!) (0.00s)
        --- PASS: TestShift/key=3/Decode() (0.00s)
        --- PASS: TestShift/key=3/Encode() (0.00s)
        --- PASS: TestShift/key=3/Decode()#01 (0.00s)
    --- PASS: TestShift/key=-3 (0.00s)
        --- PASS: TestShift/key=-3/Encode(THE_ENEMY_IS_NEAR) (0.00s)
        --- PASS: TestShift/key=-3/Decode(qebbkbjvfpkbxo) (0.00s)
        --- PASS: TestShift/key=-3/Encode(SPIES_SEND_SECRET_MESSAGES) (0.00s)
        --- PASS: TestShift/key=-3/Decode(pmfbppbkapbzobqjbppxdbp) (0.00s)
        --- PASS: TestShift/key=-3/Encode(THOMAS_JEFFERSON_DESIGNED_A_SUBSTITUTION_CIPHER) (0.00s)
        --- PASS: TestShift/key=-3/Decode(qeljxpgbccboplkabpfdkbaxprypqfqrqflkzfmebo) (0.00s)
        --- PASS: TestShift/key=-3/Encode(the_quick_brown_fox_jumps_over_the_lazy_dog) (0.00s)
        --- PASS: TestShift/key=-3/Decode(qebnrfzhyoltkclugrjmplsboqebixwvald) (0.00s)
```

```
PS C:\Users\iavto\Documents\exercism_tasks\go\simple-cipher> go test -v -run TestVig  
=== RUN   TestVigenere
=== RUN   TestVigenere/key=lemon
=== RUN   TestVigenere/key=lemon/Encode(ATTACKATDAWN)
=== RUN   TestVigenere/key=lemon/Decode(lxfopvefrnhr)
=== RUN   TestVigenere/key=abcdefghij
=== RUN   TestVigenere/key=abcdefghij/Encode(aaaaaaaaaa)
=== RUN   TestVigenere/key=abcdefghij/Decode(abcdefghij)
=== RUN   TestVigenere/key=abcdefghij/Encode(zzzzzzzzzz)
=== RUN   TestVigenere/key=abcdefghij/Decode(zabcdefghi)
=== RUN   TestVigenere/key=iamapandabear
=== RUN   TestVigenere/key=iamapandabear/Encode(I_am_a_panda_bear.)
=== RUN   TestVigenere/key=iamapandabear/Decode(qayaeaagaciai)
=== RUN   TestVigenere/key=duxrceqyaimciuucnelkeoxjhdyduu
=== RUN   TestVigenere/key=duxrceqyaimciuucnelkeoxjhdyduu/Encode(Diffie_Hellman)
=== RUN   TestVigenere/key=duxrceqyaimciuucnelkeoxjhdyduu/Decode(gccwkixcltycv)
=== RUN   TestVigenere/key=qgbvno
=== RUN   TestVigenere/key=qgbvno/Encode(cof-FEE,_123!)
=== RUN   TestVigenere/key=qgbvno/Decode(sugars)
--- PASS: TestVigenere (0.01s)
    --- PASS: TestVigenere/key=lemon (0.00s)
        --- PASS: TestVigenere/key=lemon/Encode(ATTACKATDAWN) (0.00s)
        --- PASS: TestVigenere/key=lemon/Decode(lxfopvefrnhr) (0.00s)
     [...]

2022-07-08 08:32 UTC, iAutomator commented
additionally, dedicated separate tests for checking wrong cipher keys:
- TestVigenereWrongKey
- TestWrongShiftKey

2022-07-10 11:35 UTC, andrerfcsantos approved these changes
Thanks for this!

2022-07-10 11:35 UTC, merged